-- =========================================================
-- Curated India-specific emission factors
-- Cited on /methodology — source + URL preserved for every row.
-- =========================================================

insert into public.emission_factors
(category, subcategory, name, unit, kgco2e_per_unit, region, source, source_url, year, confidence, notes)
values
-- Electricity (grid)
('electricity', 'grid_national_in', 'India grid electricity (national avg)', 'kWh', 0.7160, 'IN',
 'Central Electricity Authority (CEA) — CO2 Baseline Database, India 2023',
 'https://cea.nic.in/cdm-co2-baseline-database/', 2023, 'high',
 'National weighted average. State-level factors should be preferred where known.'),

-- LPG / PNG
('lpg', 'household_lpg', 'LPG (cylinder)', 'kg', 2.9800, 'IN',
 'IPCC 2006 Guidelines — Vol. 2 Energy, Ch. 1',
 'https://www.ipcc-nggip.iges.or.jp/public/2006gl/vol2.html', 2006, 'high',
 '~44.7 kg CO2 per 14.2 kg domestic cylinder.'),
('png', 'household_png', 'Piped Natural Gas', 'm3', 2.0200, 'IN',
 'PNGRB methodology — Natural Gas combustion',
 'https://pngrb.gov.in/', 2022, 'high', NULL),

-- Liquid fuels
('petrol', 'motor_petrol', 'Petrol (motor gasoline)', 'litre', 2.3100, 'IN',
 'DEFRA UK GHG Conversion Factors (motor gasoline)',
 'https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting',
 2024, 'high', 'Combustion only. Well-to-tank not included.'),
('diesel', 'motor_diesel', 'Diesel', 'litre', 2.6800, 'IN',
 'DEFRA UK GHG Conversion Factors (motor diesel)',
 'https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting',
 2024, 'high', 'Combustion only.'),
('cng', 'motor_cng', 'CNG (motor)', 'kg', 2.7500, 'IN',
 'IPCC 2006 — natural gas combustion',
 'https://www.ipcc-nggip.iges.or.jp/public/2006gl/vol2.html', 2006, 'high', NULL),

-- Road transport (g CO2/km converted to kg)
('transport_road', 'two_wheeler_petrol', '2-wheeler (petrol)', 'km', 0.0400, 'IN',
 'ICAT India — Transport Emission Factors',
 'https://www.icat.org.in/', 2022, 'medium', 'Indian fleet mix average.'),
('transport_road', 'car_petrol_small', 'Car (petrol, small)', 'km', 0.1420, 'IN',
 'ICAT India — Transport Emission Factors',
 'https://www.icat.org.in/', 2022, 'medium', NULL),
('transport_road', 'car_petrol_mid', 'Car (petrol, mid-size)', 'km', 0.1650, 'IN',
 'ICAT India — Transport Emission Factors',
 'https://www.icat.org.in/', 2022, 'medium', NULL),
('transport_road', 'car_diesel_mid', 'Car (diesel, mid-size)', 'km', 0.1750, 'IN',
 'ICAT India — Transport Emission Factors',
 'https://www.icat.org.in/', 2022, 'medium', NULL),
('transport_road', 'car_cng', 'Car (CNG)', 'km', 0.1100, 'IN',
 'ICAT India — Transport Emission Factors',
 'https://www.icat.org.in/', 2022, 'medium', NULL),
('transport_road', 'autorickshaw_cng', 'Auto-rickshaw (CNG)', 'km', 0.1150, 'IN',
 'ICAT India — Transport Emission Factors',
 'https://www.icat.org.in/', 2022, 'medium', NULL),
('transport_road', 'bus_diesel_per_passenger', 'Bus (diesel)', 'passenger_km', 0.0700, 'IN',
 'ICAT India — Transport Emission Factors',
 'https://www.icat.org.in/', 2022, 'medium', NULL),
('transport_road', 'taxi_petrol_per_passenger', 'Taxi (petrol, shared 1-2 pax)', 'passenger_km', 0.1500, 'IN',
 'ICAT India — Transport Emission Factors',
 'https://www.icat.org.in/', 2022, 'low', NULL),

-- Rail
('transport_rail', 'indian_railways_electric', 'Indian Railways (electrified)', 'passenger_km', 0.0080, 'IN',
 'Indian Railways Environmental Report 2022',
 'https://indianrailways.gov.in/', 2022, 'medium', NULL),
('transport_rail', 'indian_railways_diesel', 'Indian Railways (diesel)', 'passenger_km', 0.0270, 'IN',
 'Indian Railways Environmental Report 2022',
 'https://indianrailways.gov.in/', 2022, 'low', NULL),
('transport_rail', 'metro_urban', 'Urban metro (Delhi/Mumbai/Bengaluru)', 'passenger_km', 0.0140, 'IN',
 'DMRC / BMRCL annual sustainability reports',
 'https://www.delhimetrorail.com/', 2023, 'medium', NULL),

-- Air
('transport_air', 'domestic_short_haul', 'Domestic flight (short-haul, <1500 km)', 'passenger_km', 0.1330, 'IN',
 'DEFRA UK GHG Conversion Factors — domestic flight (adapted)',
 'https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting',
 2024, 'medium', NULL),
('transport_air', 'international_long_haul', 'International flight (long-haul)', 'passenger_km', 0.1480, 'IN',
 'DEFRA UK GHG Conversion Factors — long-haul flight',
 'https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting',
 2024, 'medium', 'Without radiative forcing multiplier.'),

-- Water / waste
('water', 'municipal_treated', 'Municipal treated water', 'm3', 0.3440, 'IN',
 'DEFRA water supply factor (adapted)',
 'https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting',
 2024, 'low', NULL),
('waste', 'mixed_municipal_landfill', 'Mixed municipal waste — landfill', 'kg', 0.6000, 'IN',
 'IPCC 2006 — Vol. 5 Waste',
 'https://www.ipcc-nggip.iges.or.jp/public/2006gl/vol5.html', 2006, 'medium', NULL),
('waste', 'organic_compost', 'Organic waste — composting', 'kg', 0.0500, 'IN',
 'IPCC 2006 — Vol. 5 Waste',
 'https://www.ipcc-nggip.iges.or.jp/public/2006gl/vol5.html', 2006, 'medium', NULL),
('waste', 'organic_anaerobic', 'Organic waste — anaerobic digestion', 'kg', 0.1000, 'IN',
 'IPCC 2006 — Vol. 5 Waste',
 'https://www.ipcc-nggip.iges.or.jp/public/2006gl/vol5.html', 2006, 'low', NULL),
('waste', 'mixed_municipal_recycle', 'Mixed waste — recycled (avg avoided)', 'kg', 0.1500, 'IN',
 'DEFRA waste hierarchy',
 'https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting',
 2024, 'low', 'Net of avoided emissions.'),

-- Refrigerants (GWP × kg leaked)
('refrigerant', 'r134a', 'R-134a (HFC)', 'kg', 1430.0000, 'IN',
 'IPCC AR5 GWP-100',
 'https://www.ipcc.ch/report/ar5/', 2014, 'high', 'Multiply by leakage kg/year.'),
('refrigerant', 'r410a', 'R-410A blend (HFC)', 'kg', 2088.0000, 'IN',
 'IPCC AR5 GWP-100',
 'https://www.ipcc.ch/report/ar5/', 2014, 'high', NULL),
('refrigerant', 'r404a', 'R-404A blend (HFC)', 'kg', 3922.0000, 'IN',
 'IPCC AR5 GWP-100',
 'https://www.ipcc.ch/report/ar5/', 2014, 'high', NULL),
('refrigerant', 'r290', 'R-290 (propane, natural)', 'kg', 3.0000, 'IN',
 'IPCC AR5 GWP-100',
 'https://www.ipcc.ch/report/ar5/', 2014, 'high', NULL),

-- Packaging materials
('packaging', 'plastic_pet', 'PET plastic', 'kg', 6.0000, 'IN',
 'DEFRA materials factors',
 'https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting',
 2024, 'medium', NULL),
('packaging', 'plastic_hdpe', 'HDPE plastic', 'kg', 1.9000, 'IN',
 'DEFRA materials factors',
 'https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting',
 2024, 'medium', NULL),
('packaging', 'paper_cardboard', 'Paper / cardboard', 'kg', 1.4000, 'IN',
 'DEFRA materials factors',
 'https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting',
 2024, 'medium', NULL),
('packaging', 'aluminium', 'Aluminium', 'kg', 9.0000, 'IN',
 'International Aluminium Institute — LCA 2023',
 'https://international-aluminium.org/', 2023, 'medium', NULL),
('packaging', 'glass', 'Glass', 'kg', 0.8500, 'IN',
 'DEFRA materials factors',
 'https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting',
 2024, 'medium', NULL),
('packaging', 'steel_tin', 'Steel / tin can', 'kg', 2.6000, 'IN',
 'World Steel Association LCA 2023',
 'https://worldsteel.org/', 2023, 'medium', NULL);
